# Generated by Django 5.1.2 on 2025-01-14 15:35

import apps.gestantes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.PositiveIntegerField(verbose_name='Peso pré-gestacional (kg)')),
                ('idade', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, upload_to=apps.gestantes.models.Gestante.foto_upload_path)),
                ('residencia', models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural')], default='U', max_length=1, verbose_name='Em qual tipo de área está localizada a residência da gestante?')),
                ('ocupacao_chefe_familia', models.CharField(blank=True, choices=[('NQ', 'Mão de obra não qualificada (ex.: serviços gerais, agricultura, etc.)'), ('Q', 'Mão de obra qualificada (ex.: professor, técnico, etc.)'), ('D', 'Desempregada')], max_length=2, verbose_name='Qual é a ocupação do chefe da família?')),
                ('nivel_escolaridade', models.CharField(blank=True, choices=[('NS', 'Não estudou/sabe ler e escrever'), ('FI', 'Ensino fundamental incompleto'), ('MC', 'Ensino médio completo'), ('SC', 'Ensino superior completo')], max_length=2, verbose_name='Qual é o nível de escolaridade mais alto que você completou?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestante',
                'verbose_name_plural': 'Gestantes',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('peso_atual', models.FloatField(verbose_name='Peso atual:')),
                ('periodontite', models.BooleanField(default=False, verbose_name='Você já teve periodontite (inflamação na gengiva) diagnosticada nesta gestação?')),
                ('carie_gestacao', models.BooleanField(default=False, verbose_name='Você tem ou já teve cárie nesta gestação?')),
                ('orientacao_medica', models.BooleanField(default=False, verbose_name='Você já teve orientação médica ou odontológica sobre cuidados durante a gestação?')),
                ('hipertensao_gestacao', models.BooleanField(default=False, verbose_name='Você foi diagnosticada com hipertensão (pressão alta) nesta gestação?')),
                ('dificuldade_acesso', models.BooleanField(default=False, verbose_name='Durante a gestação, você sentiu dificuldade em acessar atendimento médico ou exames necessários?')),
                ('tipo_parto', models.CharField(choices=[('Vaginal', 'Vaginal'), ('Cesáreo', 'Cesáreo')], default='Vaginal', max_length=10, verbose_name='Você pretende ter o seu filho de parto vaginal ou cesáreo?')),
                ('probabilidade_asma', models.FloatField(blank=True, null=True)),
                ('probabilidade_obesidade', models.FloatField(blank=True, null=True)),
                ('probabilidade_carie', models.FloatField(blank=True, null=True)),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='gestantes.gestante')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliação',
            },
        ),
    ]
