# Generated by Django 5.1.2 on 2025-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestante',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='gestante',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('NS', 'Não estudou/sabe ler e escrever'), ('FI', 'Ensino fundamental incompleto'), ('MC', 'Ensino médio completo'), ('SC', 'Ensino superior completo')], max_length=2, verbose_name='Como você classificaria sua renda familiar?'),
        ),
        migrations.AddField(
            model_name='gestante',
            name='vulnerabilidade_social',
            field=models.BooleanField(blank=True, default=False, verbose_name='Com base nas suas visitas domiciliares, você considera essa gestante em condição de vulnerabilidade social?'),
        ),
    ]
