# Generated by Django 5.1.2 on 2025-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='carie_gestacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='dificuldade_acesso',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='orientacao_medica',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='periodontite',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='tipo_parto',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='consumo_alcool',
            field=models.BooleanField(default=False, verbose_name='Você consome/consumiu bebidas alcoólicas (cerveja, vinho, vodka, cachaça, etc) nesta gestação?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='consumo_bebidas_adocadas',
            field=models.BooleanField(default=False, verbose_name='Na última semana você consumiu refrigerante e outras bebidas industrializadas adoçadas artificialmente, como suco de caixinha, achocolatados, etc?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='consumo_ultraprocessados',
            field=models.BooleanField(default=False, verbose_name='Na última semana você consumiu alimentos ultraprocessados (ex.: sorvete, salgadinhos, salsicha, linguiça, presuntos, macarrão instantâneo, biscoitos recheados, etc)?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='corrimento_vaginal',
            field=models.BooleanField(default=False, verbose_name='Durante a gestação, você apresentou ou apresenta corrimento vaginal frequente?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='diabetes_gestacao',
            field=models.BooleanField(default=False, verbose_name='Você foi diagnosticada com diabetes nesta gestação?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='estresse_gestacao',
            field=models.BooleanField(default=False, verbose_name='Você passou por algum estresse durante a gestação (violência, sobrecarga de trabalho)?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='fumante_gestacao',
            field=models.BooleanField(default=False, verbose_name='Você tinha o hábito de fumar ou fumou nesta gestação?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='historico_familiar_alergia',
            field=models.BooleanField(default=False, verbose_name='Algum membro da sua família (pai, mãe, irmãos) tem histórico de asma, rinite ou dermatite?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodontite_carie',
            field=models.BooleanField(default=False, verbose_name='Você já teve cárie e/ou periodontite (inflamação na gengiva) diagnosticada nesta gestação?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='probabilidade_alergia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='score_integralidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='idade_gestacional',
            field=models.PositiveIntegerField(null=True, verbose_name='Idade Gestacional (em semanas)'),
        ),
    ]
