# Generated by Django 5.1.2 on 2025-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0002_remove_avaliacao_carie_gestacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='probabilidade_alergia',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='probabilidade_asma',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='probabilidade_carie',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='probabilidade_obesidade',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='score_integralidade',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_alergia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_asma',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_carie',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_integralidade_saude',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_obesidade',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
