# Generated by Django 5.1.2 on 2025-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0002_gestante_altura_gestante_renda_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='consultas_prenatal',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade de consultas pré-natal'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='idade_gestacional',
            field=models.PositiveIntegerField(null=True, verbose_name='Idade Gestacional ou Trimestre da Gestação'),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='vulnerabilidade_social',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Com base nas suas visitas domiciliares, você considera essa gestante em condição de vulnerabilidade social?'),
        ),
    ]
