# Generated by Django 5.1.2 on 2025-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0003_avaliacao_consultas_prenatal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('BX', 'Baixa (menos de 1 salário mínimo)'), ('MD', 'Média (entre 1 e 3 salários mínimos)'), ('AT', 'Alta (mais de 3 salários mínimos)')], max_length=2, verbose_name='Como você classificaria sua renda familiar?'),
        ),
    ]
