# Generated by Django 5.1.2 on 2025-05-22 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0003_remove_avaliacao_probabilidade_alergia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_aplicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Avaliação'),
        ),
    ]
