# Generated by Django 5.1.2 on 2025-05-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0004_alter_avaliacao_data_aplicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['gestante', 'data_aplicacao'], 'verbose_name': 'Avaliacao', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
