# Generated by Django 5.1.2 on 2025-05-26 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestantes', '0005_alter_avaliacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestante',
            name='idade',
        ),
        migrations.AddField(
            model_name='gestante',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
